version: '3.7'

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
    depends_on: 
      - stunnel
  stunnel:
    build: 
      context: .
      dockerfile: Dockerfile-stunnel
